# Generated by Django 3.2 on 2021-04-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Courses',
        ),
    ]
