# Generated by Django 3.2 on 2021-04-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_lessons_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, verbose_name='Язык программирований')),
            ],
            options={
                'verbose_name': 'Язык программирований',
                'verbose_name_plural': 'Языки программирований',
            },
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='courses',
            name='count_of_lections',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лекций'),
        ),
        migrations.AddField(
            model_name='courses',
            name='duration_course',
            field=models.TimeField(blank=True, null=True, verbose_name='Длительность курса'),
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='courses',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='courses',
            name='release_date',
            field=models.DateField(auto_now=True, verbose_name='Дата выхода'),
        ),
        migrations.AddField(
            model_name='courses',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='courses',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='courses.language', verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='courses',
            name='programming_languages',
            field=models.ManyToManyField(related_name='programming_languages', to='courses.ProgrammingLanguages', verbose_name='Язык'),
        ),
    ]
