# Generated by Django 3.2 on 2021-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210425_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration_course',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность курса'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='programming_languages',
            field=models.ManyToManyField(related_name='programming_languages', to='courses.ProgrammingLanguages', verbose_name='Язык программирований'),
        ),
    ]
